//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormOturumAcmaİslemleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelGisisTablosu
    {
        public int Id { get; set; }
        public string FirsName { get; set; }
        public string LastName { get; set; }
        public string MailAdress { get; set; }
        public string Password { get; set; }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }
    }
}
